import type { Metadata } from "next";
import {  retroFont } from './fonts'
import "./globals.css";
import styles from './layout.module.css'


export const metadata: Metadata = {
  title: "Get users",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={retroFont.className}>
        <div className={styles.layout}>{children}</div></body>
    </html>
  );
}
